# Generated by Django 4.2.4 on 2023-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutdoorShelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vt_acmdfclty_nm', models.CharField(max_length=255)),
                ('dtl_adres', models.CharField(max_length=255)),
                ('xcord', models.FloatField()),
                ('ycord', models.FloatField()),
            ],
        ),
    ]
